export TERM=xterm-256color
export EDITOR=/usr/bin/nvim
export GIT_EDITOR=/usr/bin/nvim
export BROWSER=/usr/bin/google-chrome
export PATH="$HOME/.rbenv/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export GOROOT=`go env GOROOT`
export GOPATH="$HOME/.go"
export PATH="$HOME/.goenv/bin:$GOPATH/bin:$PATH"
export PATH="$HOME/.crenv/bin:$PATH"
